// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING;

// Autogenerated by clientgenerator -r AvailablePhoneNumber -m R DO NOT EDIT

package api

import (
	"github.com/exotel/goapi/assets/types"
	"github.com/exotel/goapi/resources"
)

//AvailablePhoneNumberService is the struct that defines the availablephonenumber information and has fubnctions to perform availablephonenumber level
type AvailablePhoneNumberService struct {
	Client
}

//Get sets the action as types.READ
func (__receiver_AService *AvailablePhoneNumberService) Get() *AvailablePhoneNumberService {
	if len(__receiver_AService.ResourceID) == 0 {
		__receiver_AService.action = types.BULKREAD
		__receiver_AService.data = resources.AvailablePhoneNumberFilter{}
		__receiver_AService.url = resources.AvailablePhoneNumberURLS[types.BULKREAD]
	} else {
		__receiver_AService.data = struct{}{}
		__receiver_AService.url = resources.AvailablePhoneNumberURLS[types.READ]
		__receiver_AService.action = types.READ
	}
	return __receiver_AService
}

//ID sets the id for the resource request
func (__receiver_AService *AvailablePhoneNumberService) ID(id string) *AvailablePhoneNumberService {
	__receiver_AService.ResourceID = id
	switch __receiver_AService.action {
	case types.BULKREAD:
		__receiver_AService.data = struct{}{}
		__receiver_AService.url = resources.AvailablePhoneNumberURLS[types.READ]
		__receiver_AService.action = types.READ

	}
	return __receiver_AService
}

//Filter set the filter for read operation for read
func (__receiver_AService *AvailablePhoneNumberService) Filter(filter resources.AvailablePhoneNumberFilter) *AvailablePhoneNumberService {
	__receiver_AService.data = filter
	return __receiver_AService
}

//AvailablePhoneNumber returns an instance of __receiver_AService
func (c *Client) AvailablePhoneNumber() *AvailablePhoneNumberService {
	availablephonenumberService := AvailablePhoneNumberService{Client: *c}
	availablephonenumberService.validActions = types.READ | types.BULKREAD | 0x00
	return &availablephonenumberService
}
